apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-config
  namespace: tulahack
data:
  default.conf: |
    server {
      listen                  80;
      server_name             _;
      root                    /usr/share/nginx/html;
      location / {
      proxy_read_timeout 150;
     }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tulahack-cdn
  namespace: tulahack
spec:
  selector:
    matchLabels:
      app: cdn
  replicas: 1
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cdn-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: cdn-images
          mountPath: "/usr/share/nginx/html/"
      volumes:
        - name: cdn-config
          configMap:
            name: cdn-config
        - name: cdn-images
          persistentVolumeClaim:
            claimName: tulahack-cdn
---
apiVersion: v1
kind: Service
metadata:
  name: tulahack-cdn
  namespace: tulahack
spec:
  selector:
    app: cdn
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tulahack-cdn-ingress
  namespace: tulahack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
spec:
  tls:
    - hosts:
      - tulahack.<hostname>.com
      secretName: cdn-tls
  rules:
  - host: tulahack.<hostname>.com
    http:
      paths:
      - path: /cdn
        pathType: Prefix
        backend:
          service:
            name: tulahack-cdn
            port:
              number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tulahack-cdn
  namespace: tulahack
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
